data_root_dir: /projects/prjs1814/uma_data
checkpoint_root_dir: /projects/prjs1814/uma_data/ckpt
run_dir: /projects/prjs1814/uma_data/runs/matbench
account: gusei16306
qos: ""
partition: gpu_a100
mode: SLURM
device: CUDA
ranks_per_node: 1
debug: False
mem_gb: 120
